# Generated by Django 5.2 on 2025-04-25 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_alter_user_avatar_alter_user_email_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
    ]
